set_option maxHeartbeats 4000000 in
/-- **R434 — 4+3+2 survivor dispatcher**: 56-way disjunction over
    R432's canonical survivor patterns + dispatch to the matching
    R433 per-survivor theorem.  Generated by
    `src/R434_emit_dispatcher.py`. -/
theorem compression_3_3_4_3_2_survivors_infeasible
    (χ : ℕ → ℕ)
    (hValid : IsValidColoring 27 3 χ)
    (hAvoid : AvoidsMonoSolution 3 27 χ)
    {c0 c1 c2 : ℕ}
    (hc01 : c0 ≠ c1) (hc02 : c0 ≠ c2) (hc12 : c1 ≠ c2)
    (hSurvivor :
      (χ 3 = c0 ∧ χ 6 = c0 ∧ χ 12 = c0 ∧ χ 15 = c0 ∧ χ 21 = c1 ∧ χ 24 = c1 ∧ χ 27 = c1 ∧ χ 9 = c2 ∧ χ 18 = c2) ∨
     (χ 3 = c0 ∧ χ 6 = c0 ∧ χ 12 = c0 ∧ χ 24 = c0 ∧ χ 9 = c1 ∧ χ 15 = c1 ∧ χ 27 = c1 ∧ χ 18 = c2 ∧ χ 21 = c2) ∨
     (χ 3 = c0 ∧ χ 6 = c0 ∧ χ 12 = c0 ∧ χ 24 = c0 ∧ χ 15 = c1 ∧ χ 21 = c1 ∧ χ 27 = c1 ∧ χ 9 = c2 ∧ χ 18 = c2) ∨
     (χ 3 = c0 ∧ χ 6 = c0 ∧ χ 12 = c0 ∧ χ 24 = c0 ∧ χ 9 = c1 ∧ χ 21 = c1 ∧ χ 27 = c1 ∧ χ 15 = c2 ∧ χ 18 = c2) ∨
     (χ 3 = c0 ∧ χ 6 = c0 ∧ χ 15 = c0 ∧ χ 18 = c0 ∧ χ 9 = c1 ∧ χ 21 = c1 ∧ χ 27 = c1 ∧ χ 12 = c2 ∧ χ 24 = c2) ∨
     (χ 3 = c0 ∧ χ 6 = c0 ∧ χ 15 = c0 ∧ χ 18 = c0 ∧ χ 12 = c1 ∧ χ 24 = c1 ∧ χ 27 = c1 ∧ χ 9 = c2 ∧ χ 21 = c2) ∨
     (χ 3 = c0 ∧ χ 6 = c0 ∧ χ 15 = c0 ∧ χ 18 = c0 ∧ χ 12 = c1 ∧ χ 21 = c1 ∧ χ 24 = c1 ∧ χ 9 = c2 ∧ χ 27 = c2) ∨
     (χ 3 = c0 ∧ χ 6 = c0 ∧ χ 15 = c0 ∧ χ 21 = c0 ∧ χ 12 = c1 ∧ χ 24 = c1 ∧ χ 27 = c1 ∧ χ 9 = c2 ∧ χ 18 = c2) ∨
     (χ 3 = c0 ∧ χ 6 = c0 ∧ χ 18 = c0 ∧ χ 21 = c0 ∧ χ 9 = c1 ∧ χ 15 = c1 ∧ χ 24 = c1 ∧ χ 12 = c2 ∧ χ 27 = c2) ∨
     (χ 3 = c0 ∧ χ 6 = c0 ∧ χ 18 = c0 ∧ χ 21 = c0 ∧ χ 9 = c1 ∧ χ 15 = c1 ∧ χ 27 = c1 ∧ χ 12 = c2 ∧ χ 24 = c2) ∨
     (χ 3 = c0 ∧ χ 6 = c0 ∧ χ 18 = c0 ∧ χ 21 = c0 ∧ χ 12 = c1 ∧ χ 24 = c1 ∧ χ 27 = c1 ∧ χ 9 = c2 ∧ χ 15 = c2) ∨
     (χ 9 = c0 ∧ χ 15 = c0 ∧ χ 21 = c0 ∧ χ 27 = c0 ∧ χ 3 = c1 ∧ χ 6 = c1 ∧ χ 18 = c1 ∧ χ 12 = c2 ∧ χ 24 = c2) ∨
     (χ 3 = c0 ∧ χ 6 = c0 ∧ χ 18 = c0 ∧ χ 21 = c0 ∧ χ 12 = c1 ∧ χ 15 = c1 ∧ χ 27 = c1 ∧ χ 9 = c2 ∧ χ 24 = c2) ∨
     (χ 3 = c0 ∧ χ 6 = c0 ∧ χ 18 = c0 ∧ χ 21 = c0 ∧ χ 12 = c1 ∧ χ 15 = c1 ∧ χ 24 = c1 ∧ χ 9 = c2 ∧ χ 27 = c2) ∨
     (χ 12 = c0 ∧ χ 15 = c0 ∧ χ 21 = c0 ∧ χ 24 = c0 ∧ χ 3 = c1 ∧ χ 6 = c1 ∧ χ 18 = c1 ∧ χ 9 = c2 ∧ χ 27 = c2) ∨
     (χ 3 = c0 ∧ χ 6 = c0 ∧ χ 21 = c0 ∧ χ 24 = c0 ∧ χ 12 = c1 ∧ χ 15 = c1 ∧ χ 27 = c1 ∧ χ 9 = c2 ∧ χ 18 = c2) ∨
     (χ 3 = c0 ∧ χ 6 = c0 ∧ χ 21 = c0 ∧ χ 27 = c0 ∧ χ 12 = c1 ∧ χ 15 = c1 ∧ χ 24 = c1 ∧ χ 9 = c2 ∧ χ 18 = c2) ∨
     (χ 3 = c0 ∧ χ 6 = c0 ∧ χ 24 = c0 ∧ χ 27 = c0 ∧ χ 12 = c1 ∧ χ 15 = c1 ∧ χ 21 = c1 ∧ χ 9 = c2 ∧ χ 18 = c2) ∨
     (χ 12 = c0 ∧ χ 15 = c0 ∧ χ 21 = c0 ∧ χ 24 = c0 ∧ χ 3 = c1 ∧ χ 6 = c1 ∧ χ 27 = c1 ∧ χ 9 = c2 ∧ χ 18 = c2) ∨
     (χ 3 = c0 ∧ χ 9 = c0 ∧ χ 15 = c0 ∧ χ 24 = c0 ∧ χ 6 = c1 ∧ χ 12 = c1 ∧ χ 27 = c1 ∧ χ 18 = c2 ∧ χ 21 = c2) ∨
     (χ 3 = c0 ∧ χ 9 = c0 ∧ χ 15 = c0 ∧ χ 27 = c0 ∧ χ 6 = c1 ∧ χ 12 = c1 ∧ χ 24 = c1 ∧ χ 18 = c2 ∧ χ 21 = c2) ∨
     (χ 6 = c0 ∧ χ 12 = c0 ∧ χ 24 = c0 ∧ χ 27 = c0 ∧ χ 3 = c1 ∧ χ 9 = c1 ∧ χ 15 = c1 ∧ χ 18 = c2 ∧ χ 21 = c2) ∨
     (χ 6 = c0 ∧ χ 12 = c0 ∧ χ 15 = c0 ∧ χ 24 = c0 ∧ χ 3 = c1 ∧ χ 9 = c1 ∧ χ 27 = c1 ∧ χ 18 = c2 ∧ χ 21 = c2) ∨
     (χ 3 = c0 ∧ χ 9 = c0 ∧ χ 21 = c0 ∧ χ 27 = c0 ∧ χ 6 = c1 ∧ χ 12 = c1 ∧ χ 24 = c1 ∧ χ 15 = c2 ∧ χ 18 = c2) ∨
     (χ 6 = c0 ∧ χ 12 = c0 ∧ χ 24 = c0 ∧ χ 27 = c0 ∧ χ 3 = c1 ∧ χ 9 = c1 ∧ χ 21 = c1 ∧ χ 15 = c2 ∧ χ 18 = c2) ∨
     (χ 6 = c0 ∧ χ 12 = c0 ∧ χ 21 = c0 ∧ χ 24 = c0 ∧ χ 3 = c1 ∧ χ 9 = c1 ∧ χ 27 = c1 ∧ χ 15 = c2 ∧ χ 18 = c2) ∨
     (χ 3 = c0 ∧ χ 9 = c0 ∧ χ 15 = c0 ∧ χ 21 = c0 ∧ χ 12 = c1 ∧ χ 24 = c1 ∧ χ 27 = c1 ∧ χ 6 = c2 ∧ χ 18 = c2) ∨
     (χ 3 = c0 ∧ χ 9 = c0 ∧ χ 15 = c0 ∧ χ 24 = c0 ∧ χ 6 = c1 ∧ χ 18 = c1 ∧ χ 21 = c1 ∧ χ 12 = c2 ∧ χ 27 = c2) ∨
     (χ 3 = c0 ∧ χ 9 = c0 ∧ χ 15 = c0 ∧ χ 27 = c0 ∧ χ 6 = c1 ∧ χ 18 = c1 ∧ χ 21 = c1 ∧ χ 12 = c2 ∧ χ 24 = c2) ∨
     (χ 3 = c0 ∧ χ 9 = c0 ∧ χ 15 = c0 ∧ χ 27 = c0 ∧ χ 12 = c1 ∧ χ 21 = c1 ∧ χ 24 = c1 ∧ χ 6 = c2 ∧ χ 18 = c2) ∨
     (χ 3 = c0 ∧ χ 9 = c0 ∧ χ 21 = c0 ∧ χ 27 = c0 ∧ χ 6 = c1 ∧ χ 15 = c1 ∧ χ 18 = c1 ∧ χ 12 = c2 ∧ χ 24 = c2) ∨
     (χ 3 = c0 ∧ χ 9 = c0 ∧ χ 21 = c0 ∧ χ 27 = c0 ∧ χ 12 = c1 ∧ χ 15 = c1 ∧ χ 24 = c1 ∧ χ 6 = c2 ∧ χ 18 = c2) ∨
     (χ 12 = c0 ∧ χ 15 = c0 ∧ χ 21 = c0 ∧ χ 24 = c0 ∧ χ 3 = c1 ∧ χ 9 = c1 ∧ χ 27 = c1 ∧ χ 6 = c2 ∧ χ 18 = c2) ∨
     (χ 3 = c0 ∧ χ 12 = c0 ∧ χ 15 = c0 ∧ χ 24 = c0 ∧ χ 6 = c1 ∧ χ 18 = c1 ∧ χ 21 = c1 ∧ χ 9 = c2 ∧ χ 27 = c2) ∨
     (χ 3 = c0 ∧ χ 12 = c0 ∧ χ 15 = c0 ∧ χ 24 = c0 ∧ χ 9 = c1 ∧ χ 21 = c1 ∧ χ 27 = c1 ∧ χ 6 = c2 ∧ χ 18 = c2) ∨
     (χ 3 = c0 ∧ χ 12 = c0 ∧ χ 15 = c0 ∧ χ 21 = c0 ∧ χ 6 = c1 ∧ χ 24 = c1 ∧ χ 27 = c1 ∧ χ 9 = c2 ∧ χ 18 = c2) ∨
     (χ 3 = c0 ∧ χ 12 = c0 ∧ χ 15 = c0 ∧ χ 24 = c0 ∧ χ 6 = c1 ∧ χ 21 = c1 ∧ χ 27 = c1 ∧ χ 9 = c2 ∧ χ 18 = c2) ∨
     (χ 6 = c0 ∧ χ 21 = c0 ∧ χ 24 = c0 ∧ χ 27 = c0 ∧ χ 3 = c1 ∧ χ 12 = c1 ∧ χ 15 = c1 ∧ χ 9 = c2 ∧ χ 18 = c2) ∨
     (χ 3 = c0 ∧ χ 12 = c0 ∧ χ 21 = c0 ∧ χ 24 = c0 ∧ χ 6 = c1 ∧ χ 15 = c1 ∧ χ 18 = c1 ∧ χ 9 = c2 ∧ χ 27 = c2) ∨
     (χ 3 = c0 ∧ χ 12 = c0 ∧ χ 21 = c0 ∧ χ 24 = c0 ∧ χ 9 = c1 ∧ χ 15 = c1 ∧ χ 27 = c1 ∧ χ 6 = c2 ∧ χ 18 = c2) ∨
     (χ 9 = c0 ∧ χ 15 = c0 ∧ χ 21 = c0 ∧ χ 27 = c0 ∧ χ 3 = c1 ∧ χ 12 = c1 ∧ χ 24 = c1 ∧ χ 6 = c2 ∧ χ 18 = c2) ∨
     (χ 6 = c0 ∧ χ 12 = c0 ∧ χ 21 = c0 ∧ χ 24 = c0 ∧ χ 3 = c1 ∧ χ 15 = c1 ∧ χ 18 = c1 ∧ χ 9 = c2 ∧ χ 27 = c2) ∨
     (χ 6 = c0 ∧ χ 12 = c0 ∧ χ 24 = c0 ∧ χ 27 = c0 ∧ χ 3 = c1 ∧ χ 15 = c1 ∧ χ 18 = c1 ∧ χ 9 = c2 ∧ χ 21 = c2) ∨
     (χ 3 = c0 ∧ χ 15 = c0 ∧ χ 21 = c0 ∧ χ 24 = c0 ∧ χ 6 = c1 ∧ χ 12 = c1 ∧ χ 27 = c1 ∧ χ 9 = c2 ∧ χ 18 = c2) ∨
     (χ 3 = c0 ∧ χ 15 = c0 ∧ χ 21 = c0 ∧ χ 27 = c0 ∧ χ 6 = c1 ∧ χ 12 = c1 ∧ χ 24 = c1 ∧ χ 9 = c2 ∧ χ 18 = c2) ∨
     (χ 6 = c0 ∧ χ 12 = c0 ∧ χ 24 = c0 ∧ χ 27 = c0 ∧ χ 3 = c1 ∧ χ 15 = c1 ∧ χ 21 = c1 ∧ χ 9 = c2 ∧ χ 18 = c2) ∨
     (χ 6 = c0 ∧ χ 12 = c0 ∧ χ 21 = c0 ∧ χ 24 = c0 ∧ χ 3 = c1 ∧ χ 15 = c1 ∧ χ 27 = c1 ∧ χ 9 = c2 ∧ χ 18 = c2) ∨
     (χ 6 = c0 ∧ χ 12 = c0 ∧ χ 15 = c0 ∧ χ 24 = c0 ∧ χ 3 = c1 ∧ χ 18 = c1 ∧ χ 21 = c1 ∧ χ 9 = c2 ∧ χ 27 = c2) ∨
     (χ 6 = c0 ∧ χ 12 = c0 ∧ χ 15 = c0 ∧ χ 24 = c0 ∧ χ 9 = c1 ∧ χ 21 = c1 ∧ χ 27 = c1 ∧ χ 3 = c2 ∧ χ 18 = c2) ∨
     (χ 3 = c0 ∧ χ 21 = c0 ∧ χ 24 = c0 ∧ χ 27 = c0 ∧ χ 6 = c1 ∧ χ 12 = c1 ∧ χ 15 = c1 ∧ χ 9 = c2 ∧ χ 18 = c2) ∨
     (χ 6 = c0 ∧ χ 12 = c0 ∧ χ 15 = c0 ∧ χ 24 = c0 ∧ χ 3 = c1 ∧ χ 21 = c1 ∧ χ 27 = c1 ∧ χ 9 = c2 ∧ χ 18 = c2) ∨
     (χ 6 = c0 ∧ χ 12 = c0 ∧ χ 15 = c0 ∧ χ 21 = c0 ∧ χ 3 = c1 ∧ χ 24 = c1 ∧ χ 27 = c1 ∧ χ 9 = c2 ∧ χ 18 = c2) ∨
     (χ 6 = c0 ∧ χ 12 = c0 ∧ χ 24 = c0 ∧ χ 27 = c0 ∧ χ 3 = c1 ∧ χ 18 = c1 ∧ χ 21 = c1 ∧ χ 9 = c2 ∧ χ 15 = c2) ∨
     (χ 6 = c0 ∧ χ 12 = c0 ∧ χ 21 = c0 ∧ χ 24 = c0 ∧ χ 9 = c1 ∧ χ 15 = c1 ∧ χ 27 = c1 ∧ χ 3 = c2 ∧ χ 18 = c2) ∨
     (χ 6 = c0 ∧ χ 12 = c0 ∧ χ 24 = c0 ∧ χ 27 = c0 ∧ χ 9 = c1 ∧ χ 15 = c1 ∧ χ 21 = c1 ∧ χ 3 = c2 ∧ χ 18 = c2) ∨
     (χ 9 = c0 ∧ χ 15 = c0 ∧ χ 21 = c0 ∧ χ 27 = c0 ∧ χ 6 = c1 ∧ χ 12 = c1 ∧ χ 24 = c1 ∧ χ 3 = c2 ∧ χ 18 = c2)) :
    False := by
  rcases hSurvivor with
    ⟨h3, h6, h12, h15, h21, h24, h27, h9, h18⟩ |
    ⟨h3, h6, h12, h24, h9, h15, h27, h18, h21⟩ |
    ⟨h3, h6, h12, h24, h15, h21, h27, h9, h18⟩ |
    ⟨h3, h6, h12, h24, h9, h21, h27, h15, h18⟩ |
    ⟨h3, h6, h15, h18, h9, h21, h27, h12, h24⟩ |
    ⟨h3, h6, h15, h18, h12, h24, h27, h9, h21⟩ |
    ⟨h3, h6, h15, h18, h12, h21, h24, h9, h27⟩ |
    ⟨h3, h6, h15, h21, h12, h24, h27, h9, h18⟩ |
    ⟨h3, h6, h18, h21, h9, h15, h24, h12, h27⟩ |
    ⟨h3, h6, h18, h21, h9, h15, h27, h12, h24⟩ |
    ⟨h3, h6, h18, h21, h12, h24, h27, h9, h15⟩ |
    ⟨h9, h15, h21, h27, h3, h6, h18, h12, h24⟩ |
    ⟨h3, h6, h18, h21, h12, h15, h27, h9, h24⟩ |
    ⟨h3, h6, h18, h21, h12, h15, h24, h9, h27⟩ |
    ⟨h12, h15, h21, h24, h3, h6, h18, h9, h27⟩ |
    ⟨h3, h6, h21, h24, h12, h15, h27, h9, h18⟩ |
    ⟨h3, h6, h21, h27, h12, h15, h24, h9, h18⟩ |
    ⟨h3, h6, h24, h27, h12, h15, h21, h9, h18⟩ |
    ⟨h12, h15, h21, h24, h3, h6, h27, h9, h18⟩ |
    ⟨h3, h9, h15, h24, h6, h12, h27, h18, h21⟩ |
    ⟨h3, h9, h15, h27, h6, h12, h24, h18, h21⟩ |
    ⟨h6, h12, h24, h27, h3, h9, h15, h18, h21⟩ |
    ⟨h6, h12, h15, h24, h3, h9, h27, h18, h21⟩ |
    ⟨h3, h9, h21, h27, h6, h12, h24, h15, h18⟩ |
    ⟨h6, h12, h24, h27, h3, h9, h21, h15, h18⟩ |
    ⟨h6, h12, h21, h24, h3, h9, h27, h15, h18⟩ |
    ⟨h3, h9, h15, h21, h12, h24, h27, h6, h18⟩ |
    ⟨h3, h9, h15, h24, h6, h18, h21, h12, h27⟩ |
    ⟨h3, h9, h15, h27, h6, h18, h21, h12, h24⟩ |
    ⟨h3, h9, h15, h27, h12, h21, h24, h6, h18⟩ |
    ⟨h3, h9, h21, h27, h6, h15, h18, h12, h24⟩ |
    ⟨h3, h9, h21, h27, h12, h15, h24, h6, h18⟩ |
    ⟨h12, h15, h21, h24, h3, h9, h27, h6, h18⟩ |
    ⟨h3, h12, h15, h24, h6, h18, h21, h9, h27⟩ |
    ⟨h3, h12, h15, h24, h9, h21, h27, h6, h18⟩ |
    ⟨h3, h12, h15, h21, h6, h24, h27, h9, h18⟩ |
    ⟨h3, h12, h15, h24, h6, h21, h27, h9, h18⟩ |
    ⟨h6, h21, h24, h27, h3, h12, h15, h9, h18⟩ |
    ⟨h3, h12, h21, h24, h6, h15, h18, h9, h27⟩ |
    ⟨h3, h12, h21, h24, h9, h15, h27, h6, h18⟩ |
    ⟨h9, h15, h21, h27, h3, h12, h24, h6, h18⟩ |
    ⟨h6, h12, h21, h24, h3, h15, h18, h9, h27⟩ |
    ⟨h6, h12, h24, h27, h3, h15, h18, h9, h21⟩ |
    ⟨h3, h15, h21, h24, h6, h12, h27, h9, h18⟩ |
    ⟨h3, h15, h21, h27, h6, h12, h24, h9, h18⟩ |
    ⟨h6, h12, h24, h27, h3, h15, h21, h9, h18⟩ |
    ⟨h6, h12, h21, h24, h3, h15, h27, h9, h18⟩ |
    ⟨h6, h12, h15, h24, h3, h18, h21, h9, h27⟩ |
    ⟨h6, h12, h15, h24, h9, h21, h27, h3, h18⟩ |
    ⟨h3, h21, h24, h27, h6, h12, h15, h9, h18⟩ |
    ⟨h6, h12, h15, h24, h3, h21, h27, h9, h18⟩ |
    ⟨h6, h12, h15, h21, h3, h24, h27, h9, h18⟩ |
    ⟨h6, h12, h24, h27, h3, h18, h21, h9, h15⟩ |
    ⟨h6, h12, h21, h24, h9, h15, h27, h3, h18⟩ |
    ⟨h6, h12, h24, h27, h9, h15, h21, h3, h18⟩ |
    ⟨h9, h15, h21, h27, h6, h12, h24, h3, h18⟩
  · exact compression_3_3_4_3_2_survivor01_infeasible χ hValid hAvoid
      h3 h6 h12 h15 h21 h24 h27 h9 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor02_infeasible χ hValid hAvoid
      h3 h6 h12 h24 h9 h15 h27 h18 h21 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor03_infeasible χ hValid hAvoid
      h3 h6 h12 h24 h15 h21 h27 h9 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor04_infeasible χ hValid hAvoid
      h3 h6 h12 h24 h9 h21 h27 h15 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor05_infeasible χ hValid hAvoid
      h3 h6 h15 h18 h9 h21 h27 h12 h24 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor06_infeasible χ hValid hAvoid
      h3 h6 h15 h18 h12 h24 h27 h9 h21 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor07_infeasible χ hValid hAvoid
      h3 h6 h15 h18 h12 h21 h24 h9 h27 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor08_infeasible χ hValid hAvoid
      h3 h6 h15 h21 h12 h24 h27 h9 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor09_infeasible χ hValid hAvoid
      h3 h6 h18 h21 h9 h15 h24 h12 h27 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor10_infeasible χ hValid hAvoid
      h3 h6 h18 h21 h9 h15 h27 h12 h24 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor11_infeasible χ hValid hAvoid
      h3 h6 h18 h21 h12 h24 h27 h9 h15 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor12_infeasible χ hValid hAvoid
      h9 h15 h21 h27 h3 h6 h18 h12 h24 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor13_infeasible χ hValid hAvoid
      h3 h6 h18 h21 h12 h15 h27 h9 h24 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor14_infeasible χ hValid hAvoid
      h3 h6 h18 h21 h12 h15 h24 h9 h27 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor15_infeasible χ hValid hAvoid
      h12 h15 h21 h24 h3 h6 h18 h9 h27 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor16_infeasible χ hValid hAvoid
      h3 h6 h21 h24 h12 h15 h27 h9 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor17_infeasible χ hValid hAvoid
      h3 h6 h21 h27 h12 h15 h24 h9 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor18_infeasible χ hValid hAvoid
      h3 h6 h24 h27 h12 h15 h21 h9 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor19_infeasible χ hValid hAvoid
      h12 h15 h21 h24 h3 h6 h27 h9 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor20_infeasible χ hValid hAvoid
      h3 h9 h15 h24 h6 h12 h27 h18 h21 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor21_infeasible χ hValid hAvoid
      h3 h9 h15 h27 h6 h12 h24 h18 h21 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor22_infeasible χ hValid hAvoid
      h6 h12 h24 h27 h3 h9 h15 h18 h21 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor23_infeasible χ hValid hAvoid
      h6 h12 h15 h24 h3 h9 h27 h18 h21 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor24_infeasible χ hValid hAvoid
      h3 h9 h21 h27 h6 h12 h24 h15 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor25_infeasible χ hValid hAvoid
      h6 h12 h24 h27 h3 h9 h21 h15 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor26_infeasible χ hValid hAvoid
      h6 h12 h21 h24 h3 h9 h27 h15 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor27_infeasible χ hValid hAvoid
      h3 h9 h15 h21 h12 h24 h27 h6 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor28_infeasible χ hValid hAvoid
      h3 h9 h15 h24 h6 h18 h21 h12 h27 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor29_infeasible χ hValid hAvoid
      h3 h9 h15 h27 h6 h18 h21 h12 h24 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor30_infeasible χ hValid hAvoid
      h3 h9 h15 h27 h12 h21 h24 h6 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor31_infeasible χ hValid hAvoid
      h3 h9 h21 h27 h6 h15 h18 h12 h24 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor32_infeasible χ hValid hAvoid
      h3 h9 h21 h27 h12 h15 h24 h6 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor33_infeasible χ hValid hAvoid
      h12 h15 h21 h24 h3 h9 h27 h6 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor34_infeasible χ hValid hAvoid
      h3 h12 h15 h24 h6 h18 h21 h9 h27 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor35_infeasible χ hValid hAvoid
      h3 h12 h15 h24 h9 h21 h27 h6 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor36_infeasible χ hValid hAvoid
      h3 h12 h15 h21 h6 h24 h27 h9 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor37_infeasible χ hValid hAvoid
      h3 h12 h15 h24 h6 h21 h27 h9 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor38_infeasible χ hValid hAvoid
      h6 h21 h24 h27 h3 h12 h15 h9 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor39_infeasible χ hValid hAvoid
      h3 h12 h21 h24 h6 h15 h18 h9 h27 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor40_infeasible χ hValid hAvoid
      h3 h12 h21 h24 h9 h15 h27 h6 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor41_infeasible χ hValid hAvoid
      h9 h15 h21 h27 h3 h12 h24 h6 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor42_infeasible χ hValid hAvoid
      h6 h12 h21 h24 h3 h15 h18 h9 h27 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor43_infeasible χ hValid hAvoid
      h6 h12 h24 h27 h3 h15 h18 h9 h21 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor44_infeasible χ hValid hAvoid
      h3 h15 h21 h24 h6 h12 h27 h9 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor45_infeasible χ hValid hAvoid
      h3 h15 h21 h27 h6 h12 h24 h9 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor46_infeasible χ hValid hAvoid
      h6 h12 h24 h27 h3 h15 h21 h9 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor47_infeasible χ hValid hAvoid
      h6 h12 h21 h24 h3 h15 h27 h9 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor48_infeasible χ hValid hAvoid
      h6 h12 h15 h24 h3 h18 h21 h9 h27 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor49_infeasible χ hValid hAvoid
      h6 h12 h15 h24 h9 h21 h27 h3 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor50_infeasible χ hValid hAvoid
      h3 h21 h24 h27 h6 h12 h15 h9 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor51_infeasible χ hValid hAvoid
      h6 h12 h15 h24 h3 h21 h27 h9 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor52_infeasible χ hValid hAvoid
      h6 h12 h15 h21 h3 h24 h27 h9 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor53_infeasible χ hValid hAvoid
      h6 h12 h24 h27 h3 h18 h21 h9 h15 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor54_infeasible χ hValid hAvoid
      h6 h12 h21 h24 h9 h15 h27 h3 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor55_infeasible χ hValid hAvoid
      h6 h12 h24 h27 h9 h15 h21 h3 h18 hc01 hc02 hc12
  · exact compression_3_3_4_3_2_survivor56_infeasible χ hValid hAvoid
      h9 h15 h21 h27 h6 h12 h24 h3 h18 hc01 hc02 hc12
