/-
  RadoNumbers/Breakdown.lean

  Theorem `thm:r5` ($R_5(3) > 243$) and stronger audit bound
  $R_5(3) > 296$.
  Companion to Li 2026 "On Rado Numbers for $x + by = bz$".

  Establishes that the $b^k$ pattern breaks at the verified case
  $b = 3$, $k = 5$.  Encoded via the paper's explicit 5-coloring witness
  (Appendix A) on $\{1, \ldots, 243\}$ plus a Cat 2 SAT-verified
  auxiliary SAT atom for the stronger lower bound $R_5(3) > 296$.

  Encoding:

  * `r5_witness_list` — paper's explicit 243-entry coloring.
  * `r5_witness` — coloring function `ℕ → ℕ` keyed by index.
  * `r5_witness_valid_sat` — Cat 2 SAT-verified atom asserting the
    witness is valid and avoids monochromatic solutions
    (exhaustive enumeration of all 16,362 triples in
    $\{1, \ldots, 243\}$).
  * `r5_296_sat` — Cat 2 SAT-verified atom for the stronger bound
    $R_5(3) > 296$ (public 296-point witness generated by
    `src/generate_R5_296_witness.py` and checked by
    `src/verify_R5_witness.py`).
  * `thm_r5_243`, `thm_r5_296` — derived theorems.
-/

import RadoNumbers.Basic
import Mathlib.Data.List.Basic
import Mathlib.Tactic

namespace RadoNumbers

/-! ### The explicit witness coloring (Li 2026, Appendix A). -/

/-- The 243-element witness list.  Indexing: `r5_witness_list[j-1]
    = χ(j)` for $j \in \{1, \ldots, 243\}$.  Color class sizes:
    $|C_0| = 46$, $|C_1| = 29$, $|C_2| = 54$, $|C_3| = 53$,
    $|C_4| = 61$. -/
def r5_witness_list : List ℕ :=
  [
    -- Row 1 (j = 1..27)
    0, 0, 2, 0, 0, 2, 0, 3, 1, 1, 1, 2, 3, 4, 2, 3, 4, 1, 4, 4, 2, 4, 4, 2, 4, 4, 3,
    -- Row 2 (j = 28..54)
    4, 4, 2, 4, 3, 2, 1, 3, 1, 3, 3, 2, 3, 1, 2, 3, 0, 1, 0, 0, 2, 0, 1, 2, 0, 3, 0,
    -- Row 3 (j = 55..81)
    0, 3, 2, 0, 3, 2, 3, 4, 0, 4, 4, 2, 1, 4, 2, 4, 4, 4, 4, 4, 2, 4, 4, 2, 4, 3, 4,
    -- Row 4 (j = 82..108)
    4, 3, 2, 3, 0, 2, 3, 0, 4, 3, 0, 2, 1, 0, 2, 0, 0, 3, 0, 3, 2, 1, 3, 2, 3, 1, 0,
    -- Row 5 (j = 109..135)
    3, 4, 2, 3, 4, 2, 4, 4, 3, 4, 4, 2, 4, 4, 2, 4, 3, 1, 4, 3, 2, 1, 3, 2, 3, 1, 1,
    -- Row 6 (j = 136..162)
    3, 0, 2, 0, 0, 2, 0, 1, 1, 0, 3, 2, 0, 3, 2, 0, 3, 1, 3, 4, 2, 3, 4, 2, 1, 4, 1,
    -- Row 7 (j = 163..189)
    4, 4, 2, 4, 4, 2, 4, 1, 3, 4, 3, 2, 4, 3, 2, 3, 0, 0, 3, 0, 2, 3, 0, 2, 1, 0, 0,
    -- Row 8 (j = 190..216)
    0, 0, 2, 0, 3, 2, 1, 3, 4, 3, 1, 2, 3, 4, 2, 3, 4, 4, 4, 4, 2, 4, 4, 2, 4, 4, 4,
    -- Row 9 (j = 217..243)
    4, 4, 2, 1, 3, 2, 4, 3, 1, 4, 1, 2, 3, 0, 2, 0, 0, 0, 0, 0, 2, 0, 3, 2, 0, 3, 3
  ]

/-- The witness coloring as a function `ℕ → ℕ`.  Returns
    `r5_witness_list[j - 1]` for $j \in \{1, \ldots, 243\}$ and
    `0` outside that range. -/
def r5_witness (j : ℕ) : ℕ :=
  r5_witness_list.getD (j - 1) 0

/-! ### Cat 2 atomic — SAT-verified witness validity. -/

/--
  **Cat 2 SAT-verified atom: explicit witness validity.**

  The 243-entry coloring `r5_witness` (Li 2026, Appendix A) is a
  valid 5-coloring of $\{1, \ldots, 243\}$ avoiding all
  monochromatic solutions to $x + 3·y = 3·z$.  Validity was
  independently confirmed by exhaustive enumeration of all $16{,}362$
  candidate Rado triples $(x, y, z)$ satisfying $x + 3y = 3z$ in
  $\{1, \ldots, 243\}$.

  *Status:* `gapOpen` Cat 2 (paper-cited computational
  verification; in-Lean derivation would require Mathlib `decide`
  on $\sim$16k triples, deferred).
-/
axiom r5_witness_valid_sat :
    IsValidColoring 243 5 r5_witness ∧ AvoidsMonoSolution 3 243 r5_witness

/--
  **Cat 2 SAT-verified atom: $R_5(3) > 296$.**

  Li 2026 "Breakdown of the $b^k$ Pattern": a public SAT-generated
  5-coloring of $\{1, \ldots, 296\}$ avoids every monochromatic
  solution to $x + 3y = 3z$.  The JSON witness is stored at
  `data/results/R5_witness_296.json`; `src/verify_R5_witness.py`
  independently enumerates all 24,157 candidate triples and finds no
  monochromatic triple.  Therefore $R_5(3) > 296$.

  *Status:* `gapOpen` Cat 2 (paper-cited computational
  verification; the explicit 296-point witness lives in the public data
  artifact rather than as a Lean list).
-/
axiom r5_296_sat : RadoNumberAtLeast 3 5 297

/-! ### Derived theorems. -/

/--
  **Theorem `thm:r5`.**  $R_5(3) > 243 = 3^5$.

  In particular, the $b^k$ pattern breaks for $b = 3, k = 5$.
-/
theorem thm_r5_243 : RadoNumberAtLeast 3 5 244 := by
  refine ⟨r5_witness, ?_, ?_⟩
  · -- IsValidColoring 243 5 r5_witness
    have h := r5_witness_valid_sat.1
    intro m hm_lb hm_ub
    exact h m hm_lb (by omega)
  · -- AvoidsMonoSolution 3 243 r5_witness
    have h := r5_witness_valid_sat.2
    intro hMono
    apply h
    obtain ⟨x, y, z, hxn, hyn, hzn, hRT, hxy, hyz⟩ := hMono
    exact ⟨x, y, z, by omega, by omega, by omega, hRT, hxy, hyz⟩

/--
  **Theorem `thm:r5` (stronger half).**  $R_5(3) > 296$.

  Established by incremental SAT (`r5_296_sat`) covering each
  $n \in \{244, \ldots, 296\}$.
-/
theorem thm_r5_296 : RadoNumberAtLeast 3 5 297 := r5_296_sat

/-! ### Conjectured value of $R_5(3)$.

  Auxiliary computational note: the SAT atom above records the stronger
  public lower-bound witness.  The exact value remains open. -/

end RadoNumbers
